# Linter configuruation.
[tool.isort]
profile = "black"
atomic = true
extend_skip_glob = "migrations,scripts, .vscode, __pycache__"
line_length = 88


[tool.black]
extend-exclude = "migrations,scripts, .vscode, __pycache__"
