on: [push]

jobs: 
  testing_django_project:
    steps:
      - name: first step
        uses: docker://python:3.7-alpine
        
      - name: installing docker-compose
        run: pip install docker-compose

      - name: run test
        run: docker-compose run app sh -c "python manage.py test && flake8"